
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x45clamibot
 */
public class Floor_Status_Page extends javax.swing.JPanel {
    public JButton[] tables;
    /**
     * Creates new form Floor_Status_Page
     */
    public Floor_Status_Page() {
        initComponents();
        tables = new JButton[]{Table1Button, Table2Button, Table3Button, Table4Button, Table5Button, Table6Button, Table7Button, Table8Button, Table9Button, Table10Button, Table11Button, Table12Button, Table13Button, Table14Button, Table15Button, Table16Button, Table17Button, Table18Button, Table19Button, Table20Button, Table21Button, Table22Button, Table23Button, Table24Button};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table1Button = new javax.swing.JButton();
        Table2Button = new javax.swing.JButton();
        Table3Button = new javax.swing.JButton();
        Table4Button = new javax.swing.JButton();
        Table5Button = new javax.swing.JButton();
        Table6Button = new javax.swing.JButton();
        Table7Button = new javax.swing.JButton();
        Table8Button = new javax.swing.JButton();
        Table9Button = new javax.swing.JButton();
        Table10Button = new javax.swing.JButton();
        Table11Button = new javax.swing.JButton();
        Table12Button = new javax.swing.JButton();
        Table13Button = new javax.swing.JButton();
        Table14Button = new javax.swing.JButton();
        Table15Button = new javax.swing.JButton();
        Table16Button = new javax.swing.JButton();
        Table17Button = new javax.swing.JButton();
        Table18Button = new javax.swing.JButton();
        Table19Button = new javax.swing.JButton();
        Table20Button = new javax.swing.JButton();
        Table21Button = new javax.swing.JButton();
        Table22Button = new javax.swing.JButton();
        Table23Button = new javax.swing.JButton();
        Table24Button = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        Title = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Role = new javax.swing.JScrollPane();
        RoleText = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table1Button.setBackground(new java.awt.Color(0, 255, 0));
        Table1Button.setText("Table 1");
        Table1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1ButtonMouseClicked(evt);
            }
        });
        add(Table1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 100));

        Table2Button.setBackground(new java.awt.Color(0, 255, 0));
        Table2Button.setText("Table 2");
        Table2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2ButtonMouseClicked(evt);
            }
        });
        add(Table2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 100, 100));

        Table3Button.setBackground(new java.awt.Color(0, 255, 0));
        Table3Button.setText("Table 3");
        Table3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table3ButtonMouseClicked(evt);
            }
        });
        add(Table3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 100, 100));

        Table4Button.setBackground(new java.awt.Color(0, 255, 0));
        Table4Button.setText("Table 4");
        Table4Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table4ButtonMouseClicked(evt);
            }
        });
        add(Table4Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 100, 100));

        Table5Button.setBackground(new java.awt.Color(0, 255, 0));
        Table5Button.setText("Table 5");
        Table5Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table5ButtonMouseClicked(evt);
            }
        });
        add(Table5Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 100, 100));

        Table6Button.setBackground(new java.awt.Color(0, 255, 0));
        Table6Button.setText("Table 6");
        Table6Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table6ButtonMouseClicked(evt);
            }
        });
        add(Table6Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 200, 100, 100));

        Table7Button.setBackground(new java.awt.Color(0, 255, 0));
        Table7Button.setText("Table 7");
        Table7Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table7ButtonMouseClicked(evt);
            }
        });
        add(Table7Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 200, 100, 100));

        Table8Button.setBackground(new java.awt.Color(0, 255, 0));
        Table8Button.setText("Table 8");
        Table8Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table8ButtonMouseClicked(evt);
            }
        });
        add(Table8Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 200, 100, 100));

        Table9Button.setBackground(new java.awt.Color(0, 255, 0));
        Table9Button.setText("Table 9");
        Table9Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table9ButtonMouseClicked(evt);
            }
        });
        add(Table9Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 100, 100));

        Table10Button.setBackground(new java.awt.Color(0, 255, 0));
        Table10Button.setText("Table 10");
        Table10Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table10ButtonMouseClicked(evt);
            }
        });
        add(Table10Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 100, 100));

        Table11Button.setBackground(new java.awt.Color(0, 255, 0));
        Table11Button.setText("Table 11");
        Table11Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table11ButtonMouseClicked(evt);
            }
        });
        add(Table11Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 100, 100));

        Table12Button.setBackground(new java.awt.Color(0, 255, 0));
        Table12Button.setText("Table 12");
        Table12Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table12ButtonMouseClicked(evt);
            }
        });
        add(Table12Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 100, 100));

        Table13Button.setBackground(new java.awt.Color(0, 255, 0));
        Table13Button.setText("Table 13");
        Table13Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table13ButtonMouseClicked(evt);
            }
        });
        add(Table13Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 100, 100));

        Table14Button.setBackground(new java.awt.Color(0, 255, 0));
        Table14Button.setText("Table 14");
        Table14Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table14ButtonMouseClicked(evt);
            }
        });
        add(Table14Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 400, 100, 100));

        Table15Button.setBackground(new java.awt.Color(0, 255, 0));
        Table15Button.setText("Table 15");
        Table15Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table15ButtonMouseClicked(evt);
            }
        });
        add(Table15Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 400, 100, 100));

        Table16Button.setBackground(new java.awt.Color(0, 255, 0));
        Table16Button.setText("Table 16");
        Table16Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table16ButtonMouseClicked(evt);
            }
        });
        add(Table16Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 400, 100, 100));

        Table17Button.setBackground(new java.awt.Color(0, 255, 0));
        Table17Button.setText("Table 17");
        Table17Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table17ButtonMouseClicked(evt);
            }
        });
        add(Table17Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 100, 100));

        Table18Button.setBackground(new java.awt.Color(0, 255, 0));
        Table18Button.setText("Table 18");
        Table18Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table18ButtonMouseClicked(evt);
            }
        });
        add(Table18Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 600, 100, 100));

        Table19Button.setBackground(new java.awt.Color(0, 255, 0));
        Table19Button.setText("Table 19");
        Table19Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table19ButtonMouseClicked(evt);
            }
        });
        add(Table19Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 100, 100));

        Table20Button.setBackground(new java.awt.Color(0, 255, 0));
        Table20Button.setText("Table 20");
        Table20Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table20ButtonMouseClicked(evt);
            }
        });
        add(Table20Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 100, 100));

        Table21Button.setBackground(new java.awt.Color(255, 0, 0));
        Table21Button.setText("Table 21");
        Table21Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table21ButtonMouseClicked(evt);
            }
        });
        add(Table21Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, 100, 100));

        Table22Button.setBackground(new java.awt.Color(255, 0, 0));
        Table22Button.setText("Table 22");
        Table22Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table22ButtonMouseClicked(evt);
            }
        });
        add(Table22Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 600, 100, 100));

        Table23Button.setBackground(new java.awt.Color(255, 0, 0));
        Table23Button.setText("Table 23");
        Table23Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table23ButtonMouseClicked(evt);
            }
        });
        add(Table23Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 600, 100, 100));

        Table24Button.setBackground(new java.awt.Color(255, 0, 0));
        Table24Button.setText("Table 24");
        Table24Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table24ButtonMouseClicked(evt);
            }
        });
        add(Table24Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 600, 100, 100));

        LogOutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LogOutButton.setText("Log Out");
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
        });
        add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 800, 200, 50));

        Title.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Restaurant Floor Table Status");
        Title.setViewportView(jTextArea1);

        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 800, -1));

        Role.setBorder(null);

        RoleText.setEditable(false);
        RoleText.setBackground(new java.awt.Color(240, 240, 240));
        RoleText.setColumns(20);
        RoleText.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        RoleText.setRows(5);
        RoleText.setText("Role: Waiter");
        Role.setViewportView(RoleText);

        add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 800, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Table1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1ButtonMouseClicked
        GUI.Gui.SelectTable(1);
    }//GEN-LAST:event_Table1ButtonMouseClicked

    private void Table2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2ButtonMouseClicked
        GUI.Gui.SelectTable(2);
    }//GEN-LAST:event_Table2ButtonMouseClicked

    private void Table3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table3ButtonMouseClicked
        GUI.Gui.SelectTable(3);
    }//GEN-LAST:event_Table3ButtonMouseClicked

    private void Table4ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table4ButtonMouseClicked
        GUI.Gui.SelectTable(4);
    }//GEN-LAST:event_Table4ButtonMouseClicked

    private void Table5ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table5ButtonMouseClicked
        GUI.Gui.SelectTable(5);
    }//GEN-LAST:event_Table5ButtonMouseClicked

    private void Table6ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table6ButtonMouseClicked
        GUI.Gui.SelectTable(6);
    }//GEN-LAST:event_Table6ButtonMouseClicked

    private void Table7ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table7ButtonMouseClicked
        GUI.Gui.SelectTable(7);
    }//GEN-LAST:event_Table7ButtonMouseClicked

    private void Table8ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table8ButtonMouseClicked
        GUI.Gui.SelectTable(8);
    }//GEN-LAST:event_Table8ButtonMouseClicked

    private void Table9ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table9ButtonMouseClicked
        GUI.Gui.SelectTable(9);
    }//GEN-LAST:event_Table9ButtonMouseClicked

    private void Table10ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table10ButtonMouseClicked
        GUI.Gui.SelectTable(10);
    }//GEN-LAST:event_Table10ButtonMouseClicked

    private void Table11ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table11ButtonMouseClicked
        GUI.Gui.SelectTable(11);
    }//GEN-LAST:event_Table11ButtonMouseClicked

    private void Table12ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table12ButtonMouseClicked
        GUI.Gui.SelectTable(12);
    }//GEN-LAST:event_Table12ButtonMouseClicked

    private void Table13ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table13ButtonMouseClicked
        GUI.Gui.SelectTable(13);
    }//GEN-LAST:event_Table13ButtonMouseClicked

    private void Table14ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table14ButtonMouseClicked
        GUI.Gui.SelectTable(14);
    }//GEN-LAST:event_Table14ButtonMouseClicked

    private void Table15ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table15ButtonMouseClicked
        GUI.Gui.SelectTable(15);
    }//GEN-LAST:event_Table15ButtonMouseClicked

    private void Table16ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table16ButtonMouseClicked
        GUI.Gui.SelectTable(16);
    }//GEN-LAST:event_Table16ButtonMouseClicked

    private void Table17ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table17ButtonMouseClicked
        GUI.Gui.SelectTable(17);
    }//GEN-LAST:event_Table17ButtonMouseClicked

    private void Table18ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table18ButtonMouseClicked
        GUI.Gui.SelectTable(18);
    }//GEN-LAST:event_Table18ButtonMouseClicked

    private void Table19ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table19ButtonMouseClicked
        GUI.Gui.SelectTable(19);
    }//GEN-LAST:event_Table19ButtonMouseClicked

    private void Table20ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table20ButtonMouseClicked
        GUI.Gui.SelectTable(20);
    }//GEN-LAST:event_Table20ButtonMouseClicked

    private void Table21ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table21ButtonMouseClicked
        GUI.Gui.SelectTable(21);
    }//GEN-LAST:event_Table21ButtonMouseClicked

    private void Table22ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table22ButtonMouseClicked
        GUI.Gui.SelectTable(22);
    }//GEN-LAST:event_Table22ButtonMouseClicked

    private void Table23ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table23ButtonMouseClicked
        GUI.Gui.SelectTable(23);
    }//GEN-LAST:event_Table23ButtonMouseClicked

    private void Table24ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table24ButtonMouseClicked
        GUI.Gui.SelectTable(24);
    }//GEN-LAST:event_Table24ButtonMouseClicked

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        GUI.Gui.setContentPane(GUI.Gui.loginPage);
        GUI.Gui.setVisible(true);
    }//GEN-LAST:event_LogOutButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JScrollPane Role;
    public javax.swing.JTextArea RoleText;
    private javax.swing.JButton Table10Button;
    private javax.swing.JButton Table11Button;
    private javax.swing.JButton Table12Button;
    private javax.swing.JButton Table13Button;
    private javax.swing.JButton Table14Button;
    private javax.swing.JButton Table15Button;
    private javax.swing.JButton Table16Button;
    private javax.swing.JButton Table17Button;
    private javax.swing.JButton Table18Button;
    private javax.swing.JButton Table19Button;
    private javax.swing.JButton Table1Button;
    private javax.swing.JButton Table20Button;
    private javax.swing.JButton Table21Button;
    private javax.swing.JButton Table22Button;
    private javax.swing.JButton Table23Button;
    private javax.swing.JButton Table24Button;
    private javax.swing.JButton Table2Button;
    private javax.swing.JButton Table3Button;
    private javax.swing.JButton Table4Button;
    private javax.swing.JButton Table5Button;
    private javax.swing.JButton Table6Button;
    private javax.swing.JButton Table7Button;
    private javax.swing.JButton Table8Button;
    private javax.swing.JButton Table9Button;
    private javax.swing.JScrollPane Title;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
