/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x45clamibot
 */
public class Login_Page extends javax.swing.JPanel {

    private int userID;
    private String password;
    private Employee_DB employeeDatabase;
    
    /**
     * Creates new form GUI
     */
    public Login_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        PasswordText = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        UserIDText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 200, 30));

        Password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 200, 30));

        LoginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginButton.setText("Log In");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 200, 50));

        PasswordText.setBorder(null);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Password:");
        PasswordText.setViewportView(jTextArea2);

        add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, -1, -1));

        UserIDText.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("User ID:");
        UserIDText.setViewportView(jTextArea1);

        add(UserIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        GUI.Gui.SelectLogin();
    }//GEN-LAST:event_LoginButtonMouseClicked

    public void GetLoginPage()
    {
        GUI.Gui.setContentPane(this);
    }
    
    public int SendCredentials(int ID, String password)
    {
        switch (ID)
        {
            case 0:
                return 0;
            case 1:
                return 1;
            case 2:
                return 2;
            case 3:
                return 3;
            case 4:
                return 4;
            default:
                return 0;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ID;
    private javax.swing.JButton LoginButton;
    public javax.swing.JPasswordField Password;
    private javax.swing.JScrollPane PasswordText;
    private javax.swing.JScrollPane UserIDText;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
