/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x45clamibot
 */
public class New_Order_Page extends javax.swing.JPanel {

    /**
     * Creates new form New_Order_Page
     */
    public New_Order_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ItemColumnText = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        AddItemButton = new javax.swing.JButton();
        RemoveItemButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Addmenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuarea1 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("New Order");
        Title.setViewportView(jTextArea1);

        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        ItemColumnText.setBorder(null);

        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Items:");
        ItemColumnText.setViewportView(jTextArea2);

        add(ItemColumnText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        AddItemButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddItemButton.setText("Add Item");
        add(AddItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 200, 200, 50));

        RemoveItemButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RemoveItemButton.setText("Remove Item");
        add(RemoveItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 300, 200, 50));

        BackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackButton.setText("Go Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 400, 200, 50));

        Addmenu.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Addmenu.setText("MENU");
        Addmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddmenuMouseClicked(evt);
            }
        });
        add(Addmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 120, 200, 50));

        menuarea1.setEditable(false);
        menuarea1.setColumns(20);
        menuarea1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        menuarea1.setRows(5);
        menuarea1.setText("ORDER QUEUE");
        jScrollPane1.setViewportView(menuarea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 60, 430, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        GUI.Gui.setContentPane(GUI.Gui.tableTabPage);
        GUI.Gui.setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void AddmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddmenuMouseClicked
       
        Menu.GetMenu();
        
        String output="";
       for (int i = 0; i < MenuDB.menulist.size(); i++)
            output += MenuDB.menulist.get(i) + "\n";
        menuarea1.setText(output);
       output = "";// TODO add your handling code here:
    }//GEN-LAST:event_AddmenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemButton;
    private javax.swing.JButton Addmenu;
    private javax.swing.JButton BackButton;
    private javax.swing.JScrollPane ItemColumnText;
    private javax.swing.JButton RemoveItemButton;
    private javax.swing.JScrollPane Title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextArea menuarea1;
    // End of variables declaration//GEN-END:variables
}
