/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x45clamibot
 */
public class Order_Page extends javax.swing.JPanel {

    /**
     * Creates new form New_Order_Page
     */
    public Order_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JScrollPane();
        TitleText = new javax.swing.JTextArea();
        ItemColumnText = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        AddItemButton = new javax.swing.JButton();
        RemoveItemButton = new javax.swing.JButton();
        CancelOrderButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        AddMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuarea = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBorder(null);

        TitleText.setEditable(false);
        TitleText.setBackground(new java.awt.Color(240, 240, 240));
        TitleText.setColumns(20);
        TitleText.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        TitleText.setRows(5);
        TitleText.setText("Order X Details");
        Title.setViewportView(TitleText);

        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        ItemColumnText.setBorder(null);

        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Items:");
        ItemColumnText.setViewportView(jTextArea2);

        add(ItemColumnText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        AddItemButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddItemButton.setText("Add Item");
        add(AddItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 200, 200, 50));

        RemoveItemButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RemoveItemButton.setText("Remove Item");
        add(RemoveItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 300, 200, 50));

        CancelOrderButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CancelOrderButton.setText("Cancel Order");
        add(CancelOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 400, 200, 50));

        BackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackButton.setText("Go Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 500, 200, 50));

        AddMenu.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        AddMenu.setText("MENU");
        AddMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMenuMouseClicked(evt);
            }
        });
        AddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMenuActionPerformed(evt);
            }
        });
        add(AddMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 130, 190, 40));

        menuarea.setEditable(false);
        menuarea.setColumns(20);
        menuarea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        menuarea.setRows(5);
        menuarea.setText("                                                      ORDER QUEUE");
        jScrollPane1.setViewportView(menuarea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 70, 500, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        if (GUI.Gui.GetRole() == 3)
            GUI.Gui.setContentPane(GUI.Gui.orderQueuePage); // Display order queue for cook
        else
            GUI.Gui.setContentPane(GUI.Gui.tableTabPage); // Display table tab for waiter
        GUI.Gui.setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void AddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMenuActionPerformed

    private void AddMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMenuMouseClicked
     Menu.GetMenu();
        
        String output="";
       for (int i = 0; i < MenuDB.menulist.size(); i++)
            output += MenuDB.menulist.get(i) + "\n";
        menuarea.setText(output);
       output = "";
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AddItemButton;
    public javax.swing.JButton AddMenu;
    public javax.swing.JButton BackButton;
    public javax.swing.JButton CancelOrderButton;
    private javax.swing.JScrollPane ItemColumnText;
    public javax.swing.JButton RemoveItemButton;
    private javax.swing.JScrollPane Title;
    public javax.swing.JTextArea TitleText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextArea menuarea;
    // End of variables declaration//GEN-END:variables
}
