/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x45clamibot
 */
public class Restaurant_Management_Page extends javax.swing.JPanel {

    /**
     * Creates new form Restaurant_Management_Page
     */
    public Restaurant_Management_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageEmployeesButton = new javax.swing.JButton();
        ManageInventoryButton = new javax.swing.JButton();
        ManageSalesButton = new javax.swing.JButton();
        ManageFloorPlanButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        Title = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Role = new javax.swing.JScrollPane();
        RoleText = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageEmployeesButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageEmployeesButton.setText("Manage Restaurant Employees");
        add(ManageEmployeesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 400, 100));

        ManageInventoryButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageInventoryButton.setText("Manage Restaurant Inventory");
        add(ManageInventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 400, 100));

        ManageSalesButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageSalesButton.setText("Manage Restaurant Sales");
        add(ManageSalesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 400, 100));

        ManageFloorPlanButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageFloorPlanButton.setText("Manage Restaurant Floor Plan");
        add(ManageFloorPlanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 400, 100));

        LogOutButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LogOutButton.setText("Log Out");
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
        });
        add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 800, 200, 50));

        Title.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Restaurant Management");
        Title.setViewportView(jTextArea1);

        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 50, 500, -1));

        Role.setBorder(null);

        RoleText.setEditable(false);
        RoleText.setBackground(new java.awt.Color(240, 240, 240));
        RoleText.setColumns(20);
        RoleText.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        RoleText.setRows(5);
        RoleText.setText("Role: Manager");
        Role.setViewportView(RoleText);

        add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 800, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        GUI.Gui.setContentPane(GUI.Gui.loginPage);
        GUI.Gui.setVisible(true);
    }//GEN-LAST:event_LogOutButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton ManageEmployeesButton;
    private javax.swing.JButton ManageFloorPlanButton;
    private javax.swing.JButton ManageInventoryButton;
    private javax.swing.JButton ManageSalesButton;
    private javax.swing.JScrollPane Role;
    public javax.swing.JTextArea RoleText;
    private javax.swing.JScrollPane Title;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
