/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x45clamibot
 */
public class Table_Tab_Page extends javax.swing.JPanel {

    /**
     * Creates new form Table_Tab_Page
     */
    public Table_Tab_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JScrollPane();
        TitleText = new javax.swing.JTextArea();
        AddOrderButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Order1Button = new javax.swing.JButton();
        OrderColumnText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBorder(null);

        TitleText.setEditable(false);
        TitleText.setBackground(new java.awt.Color(240, 240, 240));
        TitleText.setColumns(20);
        TitleText.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        TitleText.setRows(5);
        TitleText.setText("Table X Tab");
        Title.setViewportView(TitleText);

        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        AddOrderButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddOrderButton.setText("Add Order");
        AddOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddOrderButtonMouseClicked(evt);
            }
        });
        add(AddOrderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 200, 200, 50));

        BackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackButton.setText("Go Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 300, 200, 50));

        Order1Button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Order1Button.setText("Order 1");
        Order1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Order1ButtonMouseClicked(evt);
            }
        });
        add(Order1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, 50));

        OrderColumnText.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Orders:");
        OrderColumnText.setViewportView(jTextArea1);

        add(OrderColumnText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        GUI.Gui.setContentPane(GUI.Gui.floorStatusPage);
        GUI.Gui.setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked

    private void AddOrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddOrderButtonMouseClicked
        GUI.Gui.PlaceOrder(0);
    }//GEN-LAST:event_AddOrderButtonMouseClicked

    private void Order1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Order1ButtonMouseClicked
        GUI.Gui.GetOrder(1);
    }//GEN-LAST:event_Order1ButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOrderButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Order1Button;
    private javax.swing.JScrollPane OrderColumnText;
    public javax.swing.JScrollPane Title;
    public javax.swing.JTextArea TitleText;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
