
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x45clamibot
 */
public class Table_Status_Page extends javax.swing.JPanel {
    public JButton[] waiters;
    public int tableNo = 1;

    
    /**
     * Creates new form Floor_Status_Page
     */
    public Table_Status_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateStatusButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Status = new javax.swing.JScrollPane();
        StatusText = new javax.swing.JTextArea();
        Title = new javax.swing.JScrollPane();
        TitleText = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpdateStatusButton.setText("Update Status To Clean");
        UpdateStatusButton.setEnabled(false);
        UpdateStatusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateStatusButtonMouseClicked(evt);
            }
        });
        add(UpdateStatusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 200, 50));

        BackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackButton.setText("Go Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 200, 200, 50));

        Status.setBorder(null);
        Status.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Status.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        StatusText.setEditable(false);
        StatusText.setBackground(new java.awt.Color(200, 200, 200));
        StatusText.setColumns(20);
        StatusText.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        StatusText.setForeground(new java.awt.Color(0, 255, 0));
        StatusText.setRows(5);
        StatusText.setText("Table Is Clean");
        Status.setViewportView(StatusText);

        add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 315, 60));

        Title.setBorder(null);

        TitleText.setEditable(false);
        TitleText.setBackground(new java.awt.Color(240, 240, 240));
        TitleText.setColumns(20);
        TitleText.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        TitleText.setRows(5);
        TitleText.setText("Table X Status");
        Title.setViewportView(TitleText);

        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateStatusButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStatusButtonMouseClicked
        GUI.Gui.UpdateTableStatus();
    }//GEN-LAST:event_UpdateStatusButtonMouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        GUI.Gui.setContentPane(GUI.Gui.floorStatusPage);
        GUI.Gui.setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JScrollPane Status;
    public javax.swing.JTextArea StatusText;
    private javax.swing.JScrollPane Title;
    public javax.swing.JTextArea TitleText;
    public javax.swing.JButton UpdateStatusButton;
    // End of variables declaration//GEN-END:variables

}
