
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x45clamibot
 */
public class Waiter_Assignment_Page extends javax.swing.JPanel {
    public JButton[] waiters;

    
    /**
     * Creates new form Floor_Status_Page
     */
    public Waiter_Assignment_Page() {
        initComponents();
        waiters = new JButton[]{Waiter1Button, Waiter2Button, Waiter3Button, Waiter4Button, Waiter5Button, Waiter6Button, Waiter7Button, Waiter8Button};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Waiter1Button = new javax.swing.JButton();
        Waiter2Button = new javax.swing.JButton();
        Waiter3Button = new javax.swing.JButton();
        Waiter4Button = new javax.swing.JButton();
        Waiter5Button = new javax.swing.JButton();
        Waiter6Button = new javax.swing.JButton();
        Waiter7Button = new javax.swing.JButton();
        Waiter8Button = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        Title = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Waiter1Button.setBackground(new java.awt.Color(0, 255, 0));
        Waiter1Button.setLabel("Waiter 1");
        Waiter1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Waiter1ButtonMouseClicked(evt);
            }
        });
        add(Waiter1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, 50));

        Waiter2Button.setBackground(new java.awt.Color(0, 255, 0));
        Waiter2Button.setText("Waiter 2");
        Waiter2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Waiter2ButtonMouseClicked(evt);
            }
        });
        add(Waiter2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 200, 50));

        Waiter3Button.setBackground(new java.awt.Color(0, 255, 0));
        Waiter3Button.setText("Waiter 3");
        Waiter3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Waiter3ButtonMouseClicked(evt);
            }
        });
        add(Waiter3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 200, 50));

        Waiter4Button.setBackground(new java.awt.Color(0, 255, 0));
        Waiter4Button.setText("Waiter 4");
        Waiter4Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Waiter4ButtonMouseClicked(evt);
            }
        });
        add(Waiter4Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 200, 50));

        Waiter5Button.setBackground(new java.awt.Color(0, 255, 0));
        Waiter5Button.setText("Waiter 5");
        Waiter5Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Waiter5ButtonMouseClicked(evt);
            }
        });
        add(Waiter5Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 200, 50));

        Waiter6Button.setBackground(new java.awt.Color(0, 255, 0));
        Waiter6Button.setText("Waiter 6");
        Waiter6Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Waiter6ButtonMouseClicked(evt);
            }
        });
        add(Waiter6Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 700, 200, 50));

        Waiter7Button.setBackground(new java.awt.Color(0, 255, 0));
        Waiter7Button.setText("Waiter 7");
        Waiter7Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Waiter7ButtonMouseClicked(evt);
            }
        });
        add(Waiter7Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 200, 50));

        Waiter8Button.setBackground(new java.awt.Color(0, 255, 0));
        Waiter8Button.setText("Waiter 8");
        Waiter8Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Waiter8ButtonMouseClicked(evt);
            }
        });
        add(Waiter8Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 200, 50));

        BackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BackButton.setText("Go Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 200, 200, 50));

        Title.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Assign Waiter");
        Title.setViewportView(jTextArea1);

        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 800, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Waiter1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Waiter1ButtonMouseClicked
        GUI.Gui.AssignWaiter(1);
    }//GEN-LAST:event_Waiter1ButtonMouseClicked

    private void Waiter2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Waiter2ButtonMouseClicked
        GUI.Gui.AssignWaiter(2);
    }//GEN-LAST:event_Waiter2ButtonMouseClicked

    private void Waiter3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Waiter3ButtonMouseClicked
        GUI.Gui.AssignWaiter(3);
    }//GEN-LAST:event_Waiter3ButtonMouseClicked

    private void Waiter4ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Waiter4ButtonMouseClicked
        GUI.Gui.AssignWaiter(4);
    }//GEN-LAST:event_Waiter4ButtonMouseClicked

    private void Waiter5ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Waiter5ButtonMouseClicked
        GUI.Gui.AssignWaiter(5);
    }//GEN-LAST:event_Waiter5ButtonMouseClicked

    private void Waiter6ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Waiter6ButtonMouseClicked
        GUI.Gui.AssignWaiter(6);
    }//GEN-LAST:event_Waiter6ButtonMouseClicked

    private void Waiter7ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Waiter7ButtonMouseClicked
        GUI.Gui.AssignWaiter(7);
    }//GEN-LAST:event_Waiter7ButtonMouseClicked

    private void Waiter8ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Waiter8ButtonMouseClicked
        GUI.Gui.AssignWaiter(8);
    }//GEN-LAST:event_Waiter8ButtonMouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        GUI.Gui.setContentPane(GUI.Gui.floorStatusPage);
        GUI.Gui.setVisible(true);
    }//GEN-LAST:event_BackButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JScrollPane Title;
    private javax.swing.JButton Waiter1Button;
    private javax.swing.JButton Waiter2Button;
    private javax.swing.JButton Waiter3Button;
    private javax.swing.JButton Waiter4Button;
    private javax.swing.JButton Waiter5Button;
    private javax.swing.JButton Waiter6Button;
    private javax.swing.JButton Waiter7Button;
    private javax.swing.JButton Waiter8Button;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
